'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class langNL
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WIDM_Exam.langNL", GetType(langNL).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aflevering: .
        '''</summary>
        Friend Shared ReadOnly Property Aflevering() As String
            Get
                Return ResourceManager.GetString("Aflevering", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weet u zeker dat u de lijst leeg wilt maken? Deze actie kan niet ongedaan worden!.
        '''</summary>
        Friend Shared ReadOnly Property ClearListWarning() As String
            Get
                Return ResourceManager.GetString("ClearListWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weet u zeker dat u deze aflevering wilt verwijderen?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteEpisode() As String
            Get
                Return ResourceManager.GetString("DeleteEpisode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to We hebben gedetecteerd dat uw scherm op {0} dpi staat. Helaas ondersteunt WIDM Exam dat op het moment nog niet volledig! Hoewel het meeste goed zou moeten werken, kunnen er enkele problemen zijn. Mocht u fouten/problemen tegenkomen, stuur dan een e-mail via &quot;Contact&quot; op de website. Bij voorbaat dank..
        '''</summary>
        Friend Shared ReadOnly Property dpiMessage() As String
            Get
                Return ResourceManager.GetString("dpiMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kies eerst een map onder groepsmodus!.
        '''</summary>
        Friend Shared ReadOnly Property Folder() As String
            Get
                Return ResourceManager.GetString("Folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kies een map om de antwoorden en resultaten van te importeren. Deze zullen van dezelfde aflevering komen..
        '''</summary>
        Friend Shared ReadOnly Property FolderBrowserDialog2() As String
            Get
                Return ResourceManager.GetString("FolderBrowserDialog2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Er zijn verschillende lettertypen die gebruikt kunnen worden met WIDM Exam. De belangrijkste lettertypen, die daadwerkelijk gebruikt worden, staan aangegeven. Mocht een optie grijs zijn, betekent dit dat het lettertype niet geïnstalleerd is. Installeer dan het lettertype vanuit de map WIDM Exam. Ga hiervoor naar de map Mijn Documenten &gt; WIDM Exam &gt; Lettertypen, kies een van de mappen met het lettertype. Druk op de rechtermuisknop op het lettertype en vervolgens op &quot;Installeren&quot;..
        '''</summary>
        Friend Shared ReadOnly Property fontMessage() As String
            Get
                Return ResourceManager.GetString("fontMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (geen).
        '''</summary>
        Friend Shared ReadOnly Property geen() As String
            Get
                Return ResourceManager.GetString("geen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Groepsmodus staat aan!.
        '''</summary>
        Friend Shared ReadOnly Property GroepsmodusAan() As String
            Get
                Return ResourceManager.GetString("GroepsmodusAan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to De resultaten en antwoorden zijn geïmporteerd.
        '''</summary>
        Friend Shared ReadOnly Property ImportSuccess() As String
            Get
                Return ResourceManager.GetString("ImportSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to nl.
        '''</summary>
        Friend Shared ReadOnly Property lang() As String
            Get
                Return ResourceManager.GetString("lang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to De monitor voor de test en executie is aangepast naar monitor {0}.
        '''</summary>
        Friend Shared ReadOnly Property MonitorChanged() As String
            Get
                Return ResourceManager.GetString("MonitorChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OCR A Extended is geïnstalleerd.
        '''</summary>
        Friend Shared ReadOnly Property OCRAExtended() As String
            Get
                Return ResourceManager.GetString("OCRAExtended", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primair.
        '''</summary>
        Friend Shared ReadOnly Property Primair() As String
            Get
                Return ResourceManager.GetString("Primair", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dit scherm is {0}×{1}. Andere formaten worden passend gemaakt..
        '''</summary>
        Friend Shared ReadOnly Property Resolution() As String
            Get
                Return ResourceManager.GetString("Resolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wilt u de huidige gegevens opslaan alvorens een nieuwe aflevering te openen? Anders gaan de gegevens van deze aflevering verloren!.
        '''</summary>
        Friend Shared ReadOnly Property SaveFirst() As String
            Get
                Return ResourceManager.GetString("SaveFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verkeerde wachtwoord, start de applicatie opnieuw..
        '''</summary>
        Friend Shared ReadOnly Property WrongPass() As String
            Get
                Return ResourceManager.GetString("WrongPass", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
