'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class langEN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WIDM_Exam.langEN", GetType(langEN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Episode: .
        '''</summary>
        Friend Shared ReadOnly Property Aflevering() As String
            Get
                Return ResourceManager.GetString("Aflevering", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to clear the list? This cannot be undone!.
        '''</summary>
        Friend Shared ReadOnly Property ClearListWarning() As String
            Get
                Return ResourceManager.GetString("ClearListWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to remove this episode from?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteEpisode() As String
            Get
                Return ResourceManager.GetString("DeleteEpisode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to We have detected that your screen is at {0} dpi. Unfortunately lacks WIDM Exam some support. Most of it should work, but there may be some complications. In case you find any problems or bugs, please send an e-mail using &quot;Contact&quot; on the website. Thanks in advance.
        '''</summary>
        Friend Shared ReadOnly Property dpiMessage() As String
            Get
                Return ResourceManager.GetString("dpiMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please choose a folder under group mode first.
        '''</summary>
        Friend Shared ReadOnly Property Folder() As String
            Get
                Return ResourceManager.GetString("Folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose the folder you would like to import the answers and results from. These will be taken from the same episode..
        '''</summary>
        Friend Shared ReadOnly Property FolderBrowserDialog2() As String
            Get
                Return ResourceManager.GetString("FolderBrowserDialog2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are different fonts that can be used with WIDM Exam. The main fonts are listed. If a font is grey, it means that the font is not installed. Please install it from the folder &quot;Fonts&quot; in your WIDM Exam folder..
        '''</summary>
        Friend Shared ReadOnly Property fontMessage() As String
            Get
                Return ResourceManager.GetString("fontMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The font {0} was not found. Please install this font for this theme..
        '''</summary>
        Friend Shared ReadOnly Property FontNotInstalled() As String
            Get
                Return ResourceManager.GetString("FontNotInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (none).
        '''</summary>
        Friend Shared ReadOnly Property geen() As String
            Get
                Return ResourceManager.GetString("geen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group mode is on!.
        '''</summary>
        Friend Shared ReadOnly Property GroepsmodusAan() As String
            Get
                Return ResourceManager.GetString("GroepsmodusAan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The results and answers are successfully imported.
        '''</summary>
        Friend Shared ReadOnly Property ImportSuccess() As String
            Get
                Return ResourceManager.GetString("ImportSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to en.
        '''</summary>
        Friend Shared ReadOnly Property lang() As String
            Get
                Return ResourceManager.GetString("lang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The monitor used for the quiz and execution has been changed to monitor {0}.
        '''</summary>
        Friend Shared ReadOnly Property MonitorChanged() As String
            Get
                Return ResourceManager.GetString("MonitorChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OCR A Extended is installed.
        '''</summary>
        Friend Shared ReadOnly Property OCRAExtended() As String
            Get
                Return ResourceManager.GetString("OCRAExtended", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primary.
        '''</summary>
        Friend Shared ReadOnly Property Primair() As String
            Get
                Return ResourceManager.GetString("Primair", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This screen is {0}×{1}. Other formats will be made fit..
        '''</summary>
        Friend Shared ReadOnly Property Resolution() As String
            Get
                Return ResourceManager.GetString("Resolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the changes before exiting?.
        '''</summary>
        Friend Shared ReadOnly Property SaveChanges() As String
            Get
                Return ResourceManager.GetString("SaveChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully saved.
        '''</summary>
        Friend Shared ReadOnly Property SavedSuccess() As String
            Get
                Return ResourceManager.GetString("SavedSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save this episode&apos;s data first? If not, the data will be lost!.
        '''</summary>
        Friend Shared ReadOnly Property SaveFirst() As String
            Get
                Return ResourceManager.GetString("SaveFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose a file from the folder &quot;Afbeeldingen&quot;.
        '''</summary>
        Friend Shared ReadOnly Property WrongFolderAfbeelding() As String
            Get
                Return ResourceManager.GetString("WrongFolderAfbeelding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose a file from the folder &quot;Geluid&quot;.
        '''</summary>
        Friend Shared ReadOnly Property WrongFolderGeluid() As String
            Get
                Return ResourceManager.GetString("WrongFolderGeluid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wrong password, please restart the application..
        '''</summary>
        Friend Shared ReadOnly Property WrongPass() As String
            Get
                Return ResourceManager.GetString("WrongPass", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
